version: 2
jobs:
   build:
     docker:
       - image: circleci/node:10.1.0
       - image: mongo:3.4.4
       - image: redis
     environment: 
       MONGO_URI: mongodb://localhost:27017/aim
       DOCKERIZE_VERSION: v0.3.0
     steps:
       - checkout
       - run:
          name: get dockerize
          command: 'wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz'
       - run:
          name: wait for redis
          command: 'dockerize -wait tcp://localhost:6379 -timeout 1m'
       - run:
          name: Install babel-cli
          command: 'sudo npm install -g babel-cli'
       - run:
          name: Install npm 
          command: 'npm install'
       - run:
          name: Reload fixtures
          command: 'bin/fixture reload'
       - run:
          name: Start server
          command: 'npm start'
          background: true
   
       - run: echo "hello $MONGO_URI"
