version: 2
jobs:
   build:
     docker:
       - image: circleci/node:10.1.0
       - image: mongo:3.4.4
       - image: redis
     environment: 
       MONGO_URI: mongodb://localhost:27017/aim
       DOCKERIZE_VERSION: v0.3.0
     steps:
       - checkout
       - run:
          name: Install babel-cli
          command: 'sudo npm install -g babel-cli'
       - run:
          name: Install npm 
          command: 'npm install'
       - run:
          name: Reload fixtures
          command: 'bin/fixture reload'
       - run:
          name: Start server
          command: 'npm start'
          background: true
   
       - run: echo "hello $MONGO_URI"
